[package]
name = "ndrs"
version = "0.1.0"
authors = ["Devin Singh <drsingh2518@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3" # Graphics library
